### ISSUE TITLE
Deamon dies before being able to start child processes.

### ISSUE THREAD

**Issue by dwa012** [nevans/resque-pool#149]
I have been trying to get the daemon to start but fails due to an eventmachine error.
I setup the tasks and yml as indicated.

yaml
```
staging:
  query: 1
  email: 1
  notifications: 1
  refresh_view: 1
  download: 1
```

lib/tasks/resque.rake
```
require 'resque/tasks'
require 'resque/pool/tasks'

task "resque:setup" => :environment do
  Resque.before_fork = Proc.new do |job|
    ActiveRecord::Base.connection.disconnect!
  end
  Resque.after_fork = Proc.new do |job|
    ActiveRecord::Base.establish_connection
  end
end

task "resque:pool:setup" do
  # close any sockets or files in pool manager
  ActiveRecord::Base.connection.disconnect!
  # and re-open them in the resque worker parent
  Resque::Pool.after_prefork do |job|
    ActiveRecord::Base.establish_connection
  end
end
```

I try to run 

```
resque-pool --daemon --environment staging 
```

And get the following error for each child worker
```
/home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/eventmachine-1.0.5/lib/eventmachine.rb:673:in `connect_server': eventmachine not initialized: evma_connect_to_server (RuntimeError)
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/eventmachine-1.0.5/lib/eventmachine.rb:673:in `bind_connect'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/eventmachine-1.0.5/lib/eventmachine.rb:649:in `connect'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/redis-3.2.2/lib/redis/connection/synchrony.rb:72:in `connect'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/redis-3.2.2/lib/redis/client.rb:323:in `establish_connection'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/redis-3.2.2/lib/redis/client.rb:94:in `block in connect'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/redis-3.2.2/lib/redis/client.rb:280:in `with_reconnect'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/redis-3.2.2/lib/redis/client.rb:93:in `connect'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/redis-3.2.2/lib/redis/client.rb:351:in `ensure_connected'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/redis-3.2.2/lib/redis/client.rb:208:in `block in process'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/redis-3.2.2/lib/redis/client.rb:293:in `logging'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/redis-3.2.2/lib/redis/client.rb:207:in `process'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/redis-3.2.2/lib/redis/client.rb:113:in `call'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/redis-3.2.2/lib/redis.rb:1353:in `block in smembers'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/redis-3.2.2/lib/redis.rb:57:in `block in synchronize'
        from /home/vagrant/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/redis-3.2.2/lib/redis.rb:57:in `synchronize'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/redis-3.2.2/lib/redis.rb:1352:in `smembers'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:393:in `call_with_namespace'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:290:in `method_missing'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/resque-1.25.2/lib/resque.rb:259:in `queues'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/resque-1.25.2/lib/resque/worker.rb:311:in `glob_match'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/resque-1.25.2/lib/resque/worker.rb:302:in `block in queues'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/resque-1.25.2/lib/resque/worker.rb:300:in `map'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/resque-1.25.2/lib/resque/worker.rb:300:in `queues'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/resque-pool-0.6.0/lib/resque/pool.rb:316:in `block in reap_all_workers'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/resque-pool-0.6.0/lib/resque/pool.rb:310:in `loop'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/resque-pool-0.6.0/lib/resque/pool.rb:310:in `reap_all_workers'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/resque-pool-0.6.0/lib/resque/pool.rb:280:in `block in join'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/resque-pool-0.6.0/lib/resque/pool.rb:279:in `loop'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/resque-pool-0.6.0/lib/resque/pool.rb:279:in `join'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/resque-pool-0.6.0/lib/resque/pool.rb:89:in `run'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/resque-pool-0.6.0/lib/resque/pool/tasks.rb:17:in `block (2 levels) in <top (required)>'
        from /home/vagrant/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `call'
        from /home/vagrant/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
        from /home/vagrant/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `each'
        from /home/vagrant/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
        from /home/vagrant/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
        from /home/vagrant/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
        from /home/vagrant/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
        from /home/vagrant/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/resque-pool-0.6.0/lib/resque/pool/cli.rb:148:in `start_pool'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/resque-pool-0.6.0/lib/resque/pool/cli.rb:20:in `run'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/gems/resque-pool-0.6.0/bin/resque-pool:7:in `<top (required)>'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/bin/resque-pool:23:in `load'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/bin/resque-pool:23:in `<main>'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/bin/ruby_executable_hooks:15:in `eval'
        from /home/vagrant/.rvm/gems/ruby-2.2.2@global/bin/ruby_executable_hooks:15:in `<main>'
```

Any help would be appreciated!

Edit:

I can get the pool up and running using the following
```
rake --trace resque:pool
```

Just not with the daemon tool

**Comment by dwa012** [comment]
Looks like the problem was with the default redis driver.

Switching to hiredis fixed the problem https://github.com/redis/hiredis-rb

https://github.com/websocket-rails/websocket-rails/issues/29#issuecomment-11271142
